### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by PingLord1** [rizecookey/CookeyMod#1]
![Screenshot 2020-11-29 215635](https://user-images.githubusercontent.com/75210632/100544308-b5fe8300-328f-11eb-98bf-ca0b42698721.png)

**Comment by rizecookey** [comment]
Please sent the crash report (click "View crash report"), save it somewhere and send it here.

**Comment by rizecookey** [comment]
Issue should be fixed, see https://github.com/rizecookey/CookeyMod/releases/tag/1.3.1
