### ISSUE TITLE
Fix incompatibility with Hit Color by lluurii11

### ISSUE THREAD

**Issue by ranofeef** [rizecookey/CookeyMod#14]
i want to use this mod cuz of the hit animation, but i found  lluurii11's mod more convenient cuz his mod can change hit color by scrolling, so maybe u can send this mod without the damage color section(1.20.1)

**Comment by ranofeef** [comment]
but i cant change the hit color by scrolling now, i can only change the hit color by changing the code which is not tht convenient compare to lluurii11 hit color mod

**Comment by ranofeef** [comment]
or u can make an update to change the hit color by scrolling just like the mod

**Comment by ranofeef** [comment]
here is the mod review:https://www.youtube.com/watch?v=xczIdIOJWuY&t=4s
it is actually very convenient, so i hope u can fix this incompatibility(like maybe make them work both ways) or either give me the version of the mod which damage color section is removed

**Comment by rizecookey** [comment]
CookeyMod already has sliders for color selection, that option was added in version 1.7.8. I'd recommend you download the newest version on the [releases page](https://github.com/rizecookey/CookeyMod/releases).
