### ISSUE TITLE
hit color won't get some colors

### ISSUE THREAD

**Issue by KillerPenguin9** [rizecookey/CookeyMod#8]
I can't get the hit color to change to blue or purple can someone help me or explain how the color code works

**Comment by rizecookey** [comment]
See my comment here: https://github.com/rizecookey/CookeyMod/issues/5#issuecomment-2366724314

**Comment by penguinX9games** [comment]
Ok thanks

**Comment by rizecookey** [comment]
I've added some sliders to make picking a color easier with release [1.7.8](https://github.com/rizecookey/CookeyMod/releases/tag/1.7.8%2B1.21.1).
